kit1:
  Inv: 27;
  Title: Kit 1
  Item: chest

kit2:
  Inv: 27;
  Title: Kit 2
  Item: chest
 
kit3:
  Inv: 27;
  Title: Kit 3
  Item: chest

kit4:
  Inv: 27;
  Title: Kit 4
  Item: chest

kit5:
  Inv: 27;
  Title: Kit 5
  Item: chest

kit6:
  Inv: 27;
  Title: Kit 6
  Item: chest

kit7:
  Inv: 27;
  Title: Kit 7
  Item: chest

kit8:
  Inv: 27;
  Title: Kit 8
  Item: chest

kit9:
  Inv: 27;
  Title: Kit 9
  Item: chest